<a href="https://colab.research.google.com/github/PrinceDaveIgnacio/58013_LINEAR_ALGEBRA/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1.

In [53]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
D = np.array([[1,2],[3,4]])

##OUTPUTS OF THE ARRAYS FOR TESTING
#print( A)
#print(B)
#print(C)
#print(D)

#Answers starts here below:
#PROBLEM1


#a. AB
a = np.dot(A,B)
print("Answer a: \n", a)
#b. D + D
b = np.add(D,D)
print("Answer b: \n" , b)

#c. 2C
c = np.multiply(2,C)
print("Answer c: \n", c)

Answer a: 
 [[22 28]
 [49 64]]
Answer b: 
 [[2 4]
 [6 8]]
Answer c: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2.

In [57]:
#cross product

A2 = np.array([2,7,4])
B2 = np.array([3,9,8])

cp = np.cross(A2,B2)
print("A2 x B2 \n")
print("[2,7,4] x [3,9,8] \n")

print("Answer: \n")
print(cp)

A2 x B2 

[2,7,4] x [3,9,8] 

Answer: 

[20 -4 -3]
