<a href="https://colab.research.google.com/github/PrinceDaveIgnacio/58013_LINEAR_ALGEBRA/blob/main/Python%20Exercise%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

print(A+B+C)


##Additon
D = np.add(A,np.add(B,C))

print(np.sum(B))
print(D)

[ 4  3 -1]
2
[ 4  3 -1]


In [6]:
##Subtraction
np.subtract(A,B)

A-B


array([-2,  1,  2])

In [5]:
##Multiplication
np.multiply(A,B)

A*B


array([3, 2, 0])

In [4]:
##Division
np.divide(A,B)

A/B

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C//D

np.array(A/B,dtype=int)


array([0, 2, 0])