<a href="https://colab.research.google.com/github/PrinceDaveIgnacio/58013_LINEAR_ALGEBRA/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Systems of Linear Equation**

In [1]:
import numpy as np




X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)



print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


**Coding** **Activity** **10**

In [7]:
#bakeryshop
#purchasing supply
#flour Yeast Egg
#Every month purchase
#30 sacks of flour, 10 packs of yeast, 120 eggs for 12,500 pesos
purch_all= np.array([
      [30,10,120],
      [40,20,200],
      [50,40,360],
      ])


costpurch_all = np.array([
    [12000], [18000],[25700]
])

#PROMO FOR EVERY 2 MONTHS OF PURCHASING
#40 sacks of flour, 20 packs of yeast, and 200 eggs for 18000

#PROMO FOR EVERY 3 MONTHS OF PURCHASING
#50 sacks of flour, 40 packs of yeast, and 360 eggs for 25700


cost_eff = np.linalg.solve(purch_all,costpurch_all)

print(cost_eff)
print()


[[430.]
 [690.]
 [-65.]]
