<a href="https://colab.research.google.com/github/PrinceDaveIgnacio/58013_LINEAR_ALGEBRA/blob/main/Python_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Coding Activity**

In [ ]:
import numpy as np


A = np.array([[-0.4],[4.3],[-0.6]])
B = np.array([0,20,21])
C = np.array([-0.2, 1, -1.5])

In [ ]:
A

array([[-0.4],
       [ 4.3],
       [-0.6]])

In [ ]:
B

array([-0.2, 21. ])

In [ ]:
C

array([-0.2,  1. , -1.5])

# **Vector Operation**

In [ ]:
#individual vector sum

ec_sum1 = np.sum(A)
vec_sum2 = np.sum(B)
vec_sum3 = np.sum(C)

print(vec_sum1)
print(vec_sum2)
print(vec_sum3)

3.3
41
-0.7


# **Scalar Multiplication**

In [ ]:
sca_mul1 = np.multiply(A,B)
sca_mul2 = np.multiply(A,C)
sca_mul3 = np.multiply(C,B)

print(" A x B \n"  )
print(sca_mul1)
print("\n")
print(" A x C \n"  )
print(sca_mul2)
print("\n")
print(" C x B \n"  )
print(sca_mul3)

 A x B 

[[ -0.   -8.   -8.4]
 [  0.   86.   90.3]
 [ -0.  -12.  -12.6]]


 A x C 

[[ 0.08 -0.4   0.6 ]
 [-0.86  4.3  -6.45]
 [ 0.12 -0.6   0.9 ]]


 C x B 

[ -0.   20.  -31.5]


# **Vector Subtraction**

In [ ]:
vec_sub1 = np.subtract(A,B)
vec_sub2 = np.subtract(A,C)
vec_sub3 = np.subtract(C,B)

print(" A - B \n"  )
print(vec_sub1)
print("\n")
print(" A - C \n"  )
print(vec_sub1)
print("\n")
print(" C - B \n"  )
print(vec_sub3)

 A - B 

[[ -0.4 -20.4 -21.4]
 [  4.3 -15.7 -16.7]
 [ -0.6 -20.6 -21.6]]


 A - C 

[[ -0.4 -20.4 -21.4]
 [  4.3 -15.7 -16.7]
 [ -0.6 -20.6 -21.6]]


 C - B 

[ -0.2 -19.  -22.5]


# **Dot product**

In [ ]:
val3 = np.dot(C,B)
print(val3)

-11.5
