<a href="https://colab.research.google.com/github/PrinceDaveIgnacio/58013_LINEAR_ALGEBRA/blob/main/Vector%2C_Spaces%2C_and_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector', A)
print('Vector', B)

Vector [4 3]
Vector [ 2 -5]


Side Dimension, Size

In [36]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

#ball = np.vstack((ball1,ball2))
ball = np.shape(ball1)
balls = np.shape(ball2)
z = ball + balls
print(z)
x = np.i0(ball1)

print(x)

(3, 3)
[1.26606588 2.2795853  4.88079259]


Vector
Scalar
Tensor

Addition of Vector

In [64]:
import numpy as np

#addiiton of vector

A = np.array([4,3])
B  = np.array([2,-5])
R = np.add(A,B)
print(R)

#subtraction

R1 = np.subtract(A,B)
R1_1 = np.subtract(B,A)
print(R1_1)
print(R1)


#Scalar Product

Num1 = np.array([2,4,6])
R1_2 = np.multiply(A,B)
print(R1_2)

#Scalar Product Sample 2

S = np.array([2])
V = S * A

print(V)


#Dot Product
dotprod = np.multiply(A,B)

print(dotprod)

[ 6 -2]
[-2 -8]
[2 8]
[  8 -15]
[8 6]
[  8 -15]


In [74]:
#Property of matrix

#identity matrix
#all diagonals are one
A = np.eye(2,5)

print(A)

#Zero Matrix
B = np.zeros([5,5])

print(B)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [76]:
e = np.full((3,3), 7)
print(e)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [78]:
#transpose matrix
A1 = np.array([4,3])
trans = np.transpose(A1)
print(trans)

[4 3]
